services:
  lehrium_backend:
    container_name: lehrium_backend
    environment:
      - DB_URL=lehrium_db:5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=lehrium
      - UNTIS_USERNAME=..
      - UNTIS_PASSWORD=..
      - GIN_PORT=8081
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
       - "8080:8080"
  lehrium_frontend:
    container_name: lehrium_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
       - "8081:8081"
    environment:
       - GIN_MODE=release
       - LEHRIUM_FRONTEND_DEBUG=false
       - GIN_PORT=8081
  lehrium_db:
    image: postgres:latest
    container_name: lehrium_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lehrium
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: