services:
  lehrium_db:
    image: postgres:latest
    container_name: lehrium_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lehrium
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  lehrium_backend:
    container_name: lehrium_backend
    environment:
      - GIN_MODE=release
      - DB_HOST=lehrium_db
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=lehrium
      - DB_SCHEMA=public
      - UNTIS_USERNAME=..
      - UNTIS_PASSWORD=..
      - PORT=8080
      - JWT_SECRET=changeme
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
       - "8080:8080"
    depends_on:
      - lehrium_db
  lehrium_frontend:
    container_name: lehrium_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
       - "8081:8081"
    environment:
       - GIN_MODE=release
       - LEHRIUM_FRONTEND_DEBUG=false
       - GIN_PORT=8081
    depends_on:
      - lehrium_backend
volumes:
  postgres_data: